"""Generate a hash-checked lock from the validated Python 3.12 environment."""

from __future__ import annotations

import importlib.metadata
import json
import os
import tempfile
import tomllib
import urllib.request
from collections import deque
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name
from packaging.version import Version

ROOT = Path(__file__).parents[1]
EXCLUDED_TOOLS = {"pip", "pip-tools", "uv", "wheel"}


def _project_roots() -> set[str]:
    data = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    project = data["project"]
    requirements = [
        *project["dependencies"],
        *project["optional-dependencies"]["dev"],
    ]
    return {canonicalize_name(Requirement(item).name) for item in requirements}


def _closure() -> dict[str, importlib.metadata.Distribution]:
    result: dict[str, importlib.metadata.Distribution] = {}
    pending = deque(sorted(_project_roots()))
    while pending:
        name = pending.popleft()
        if name in result or name in EXCLUDED_TOOLS:
            continue
        try:
            distribution = importlib.metadata.distribution(name)
        except importlib.metadata.PackageNotFoundError as error:
            raise RuntimeError(f"Required distribution is not installed: {name}") from error
        result[name] = distribution
        for raw_requirement in distribution.requires or ():
            requirement = Requirement(raw_requirement)
            if requirement.marker is not None and not requirement.marker.evaluate():
                continue
            dependency = canonicalize_name(requirement.name)
            if dependency not in result:
                pending.append(dependency)
    return result


def _hashes(name: str, version: str) -> tuple[str, ...]:
    public_version = Version(version).public
    url = f"https://pypi.org/pypi/{name}/{public_version}/json"
    with urllib.request.urlopen(url, timeout=30) as response:
        payload = json.load(response)
    hashes = sorted(
        {
            item["digests"]["sha256"]
            for item in payload["urls"]
            if item.get("digests", {}).get("sha256")
        }
    )
    if not hashes:
        raise RuntimeError(f"PyPI returned no SHA-256 artifacts for {name}=={public_version}")
    return tuple(hashes)


def generate(output: str | Path = ROOT / "requirements.lock") -> Path:
    """Write a deterministic pip-compatible lock with artifact SHA-256 hashes."""
    lines = [
        "# Generated by tools/generate_lock.py from the validated Python 3.12 environment.",
        "# Regenerate after any dependency range or validation-environment change.",
        "",
    ]
    for name, distribution in sorted(_closure().items()):
        version = Version(distribution.version).public
        hashes = _hashes(name, distribution.version)
        lines.append(f"{name}=={version} \\")
        for index, digest in enumerate(hashes):
            continuation = " \\" if index < len(hashes) - 1 else ""
            lines.append(f"    --hash=sha256:{digest}{continuation}")
    target = Path(output)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{target.name}.",
        suffix=".tmp",
        dir=target.parent,
    )
    os.close(descriptor)
    temporary = Path(temporary_name)
    try:
        temporary.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
        os.replace(temporary, target)
    finally:
        temporary.unlink(missing_ok=True)
    return target


if __name__ == "__main__":
    print(generate())
